import "server-only";
import './globals.css'

import ThemeWrapper from '../components/ThemeWrapper';

import { Roboto } from '@next/font/google';

import SupabaseAuthProvider from "@/components/providers/supabase-auth-provider";
import SupabaseProvider from "@/components/providers/supabase-provider";
import { createClient } from "@/utils/supabase-server";

export const metadata = {
  title: 'Eternal Place Memorial Park',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  subsets: ['latin'],
  weight: '400'
});

export default async function RootLayout({ children }) {
  const supabase = createClient();
  const { data: { session }, } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body className={roboto.className}>
        <SupabaseProvider>
          <SupabaseAuthProvider serverSession={session}>
            <ThemeWrapper children={children} />
          </SupabaseAuthProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
