import './globals.css'

import ThemeWrapper from './components/ThemeWrapper';

export const metadata = {
  title: 'Eternal Place Memorial Park',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeWrapper children={children} />
      </body>
    </html>
  )
}
