import "server-only";
import './globals.css'

import ThemeWrapper from './components/ThemeWrapper';

import SupabaseAuthProvider from "@/app/components/providers/supabase-auth-provider";
import SupabaseProvider from "@/app/components/providers/supabase-provider";
import { createClient } from "@/utils/supabase-server";

export const metadata = {
  title: 'Eternal Place Memorial Park',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const supabase = createClient();
  const { data: { session }, } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body>
        <SupabaseProvider>
          <SupabaseAuthProvider serverSession={session}>
            <ThemeWrapper children={children} />
          </SupabaseAuthProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
